### ISSUE TITLE
Add license information

### ISSUE THREAD

**Issue by vazhnov** [humancomputerintegration/ecoEDA#1]
Hello!

I found your project from https://hackaday.com/2023/10/28/ecoeda-integrates-your-junk-bin-into-your-designs/

Could you please add information about the license of this repository — is it allowed to copy, change and use the code in any purpose?
It would be great to see any popular open source license.

**Comment by xjasminelu** [comment]
Hi Alexey!

Thanks so much for bringing this up! It slipped our mind but we're super excited to make it open source! We have now added the GNU GPL to our repository.

**Comment by vazhnov** [comment]
GPL v3 — amazing!
Thank you!

**Comment by Senna-Code** [comment]
I think that an open sourced catalog of devices to salvaged components is key in enabling this tool to work to its maximum efficiency.


I have access to fair bit of e-waste components and can easily get access to more
-I am happy to provide some lists of salvageable components and/or hi-def images of the boards if others are interested
